# description under construction

In [ ]:
import sidrapy

In [ ]:
data = sidrapy.get_table(
                table_code="4709",
                territorial_level="6",
                ibge_territorial_code="all",
                variable="93"
            )

In [ ]:
data

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N
0,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Variável (Código),Variável,Ano (Código),Ano
1,6,Município,45,Pessoas,21494,1100015,Alta Floresta D'Oeste - RO,93,População residente,2022,2022
2,6,Município,45,Pessoas,96833,1100023,Ariquemes - RO,93,População residente,2022,2022
3,6,Município,45,Pessoas,5351,1100031,Cabixi - RO,93,População residente,2022,2022
4,6,Município,45,Pessoas,86887,1100049,Cacoal - RO,93,População residente,2022,2022
...,...,...,...,...,...,...,...,...,...,...,...
5566,6,Município,45,Pessoas,14956,5222005,Vianópolis - GO,93,População residente,2022,2022
5567,6,Município,45,Pessoas,8768,5222054,Vicentinópolis - GO,93,População residente,2022,2022
5568,6,Município,45,Pessoas,4215,5222203,Vila Boa - GO,93,População residente,2022,2022
5569,6,Município,45,Pessoas,5815,5222302,Vila Propício - GO,93,População residente,2022,2022
5570,6,Município,45,Pessoas,2817381,5300108,Brasília - DF,93,População residente,2022,2022

In [ ]:
df = data[1:].copy()

In [ ]:
df

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N
1,6,Município,45,Pessoas,21494,1100015,Alta Floresta D'Oeste - RO,93,População residente,2022,2022
2,6,Município,45,Pessoas,96833,1100023,Ariquemes - RO,93,População residente,2022,2022
3,6,Município,45,Pessoas,5351,1100031,Cabixi - RO,93,População residente,2022,2022
4,6,Município,45,Pessoas,86887,1100049,Cacoal - RO,93,População residente,2022,2022
5,6,Município,45,Pessoas,15890,1100056,Cerejeiras - RO,93,População residente,2022,2022
...,...,...,...,...,...,...,...,...,...,...,...
5566,6,Município,45,Pessoas,14956,5222005,Vianópolis - GO,93,População residente,2022,2022
5567,6,Município,45,Pessoas,8768,5222054,Vicentinópolis - GO,93,População residente,2022,2022
5568,6,Município,45,Pessoas,4215,5222203,Vila Boa - GO,93,População residente,2022,2022
5569,6,Município,45,Pessoas,5815,5222302,Vila Propício - GO,93,População residente,2022,2022
5570,6,Município,45,Pessoas,2817381,5300108,Brasília - DF,93,População residente,2022,2022

In [ ]:
df[["D1N", "UF"]] = df["D1N"].str.split(" - ", n=1, expand=True)

In [ ]:
df

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,UF
1,6,Município,45,Pessoas,21494,1100015,Alta Floresta D'Oeste,93,População residente,2022,2022,RO
2,6,Município,45,Pessoas,96833,1100023,Ariquemes,93,População residente,2022,2022,RO
3,6,Município,45,Pessoas,5351,1100031,Cabixi,93,População residente,2022,2022,RO
4,6,Município,45,Pessoas,86887,1100049,Cacoal,93,População residente,2022,2022,RO
5,6,Município,45,Pessoas,15890,1100056,Cerejeiras,93,População residente,2022,2022,RO
...,...,...,...,...,...,...,...,...,...,...,...,...
5566,6,Município,45,Pessoas,14956,5222005,Vianópolis,93,População residente,2022,2022,GO
5567,6,Município,45,Pessoas,8768,5222054,Vicentinópolis,93,População residente,2022,2022,GO
5568,6,Município,45,Pessoas,4215,5222203,Vila Boa,93,População residente,2022,2022,GO
5569,6,Município,45,Pessoas,5815,5222302,Vila Propício,93,População residente,2022,2022,GO
5570,6,Município,45,Pessoas,2817381,5300108,Brasília,93,População residente,2022,2022,DF

In [ ]:
df.loc[df["D1N"] == "Curitiba - PR"]

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,UF
4006,6,Município,45,Pessoas,1773718,4106902,Curitiba - PR,93,População residente,2022,2022,RO

In [ ]:
dfpr = df.loc[df["UF"] == "PR"]

In [ ]:
dfpr = df[df["UF"] == "PR"]

In [ ]:
dfpr

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,UF
3913,6,Município,45,Pessoas,7241,4100103,Abatiá,93,População residente,2022,2022,PR
3914,6,Município,45,Pessoas,6256,4100202,Adrianópolis,93,População residente,2022,2022,PR
3915,6,Município,45,Pessoas,10233,4100301,Agudos do Sul,93,População residente,2022,2022,PR
3916,6,Município,45,Pessoas,119825,4100400,Almirante Tamandaré,93,População residente,2022,2022,PR
3917,6,Município,45,Pessoas,3590,4100459,Altamira do Paraná,93,População residente,2022,2022,PR
...,...,...,...,...,...,...,...,...,...,...,...,...
4307,6,Município,45,Pessoas,3055,4128625,Alto Paraíso,93,População residente,2022,2022,PR
4308,6,Município,45,Pessoas,5697,4128633,Doutor Ulysses,93,População residente,2022,2022,PR
4309,6,Município,45,Pessoas,3811,4128658,Virmond,93,População residente,2022,2022,PR
4310,6,Município,45,Pessoas,9706,4128708,Vitorino,93,População residente,2022,2022,PR
4311,6,Município,45,Pessoas,5798,4128807,Xambrê,93,População residente,2022,2022,PR

In [ ]:
dfpr = dfpr.reset_index(drop=True)

In [ ]:
dfpr

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,UF
0,6,Município,45,Pessoas,7241,4100103,Abatiá,93,População residente,2022,2022,PR
1,6,Município,45,Pessoas,6256,4100202,Adrianópolis,93,População residente,2022,2022,PR
2,6,Município,45,Pessoas,10233,4100301,Agudos do Sul,93,População residente,2022,2022,PR
3,6,Município,45,Pessoas,119825,4100400,Almirante Tamandaré,93,População residente,2022,2022,PR
4,6,Município,45,Pessoas,3590,4100459,Altamira do Paraná,93,População residente,2022,2022,PR
...,...,...,...,...,...,...,...,...,...,...,...,...
394,6,Município,45,Pessoas,3055,4128625,Alto Paraíso,93,População residente,2022,2022,PR
395,6,Município,45,Pessoas,5697,4128633,Doutor Ulysses,93,População residente,2022,2022,PR
396,6,Município,45,Pessoas,3811,4128658,Virmond,93,População residente,2022,2022,PR
397,6,Município,45,Pessoas,9706,4128708,Vitorino,93,População residente,2022,2022,PR
398,6,Município,45,Pessoas,5798,4128807,Xambrê,93,População residente,2022,2022,PR

In [ ]:
dfpr[dfpr["D1N"] == "Foz do Iguaçu"]

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,UF
4031,6,Município,45,Pessoas,285415,4108304,Foz do Iguaçu,93,População residente,2022,2022,PR