In [1]:
import geobr as gbr

In [2]:
df = gbr.read_census_tract(code_tract="PR", year=2022)

In [3]:
df

,code_tract,code_muni,name_muni,name_neighborhood,code_neighborhood,code_subdistrict,name_subdistrict,code_district,name_district,code_urban_concentration,...,name_immediate,code_intermediate,name_intermediate,code_region,name_region,situacao,code_situacao,code_type,area_km2,geometry
0,4.100103e+14,4100103.0,Abatiá,None,NaN,4.100103e+10,None,410010305.0,Abatiá,NaN,...,Santo Antônio da Platina,4105.0,Londrina,4.0,Sul,Urbana,1.0,0.0,0.190655,"MULTIPOLYGON (((-50.31087 -23.29868, -50.31698..."
1,4.100103e+14,4100103.0,Abatiá,None,NaN,4.100103e+10,None,410010305.0,Abatiá,NaN,...,Santo Antônio da Platina,4105.0,Londrina,4.0,Sul,Urbana,1.0,0.0,0.279183,"MULTIPOLYGON (((-50.31206 -23.30683, -50.30736..."
2,4.100103e+14,4100103.0,Abatiá,None,NaN,4.100103e+10,None,410010305.0,Abatiá,NaN,...,Santo Antônio da Platina,4105.0,Londrina,4.0,Sul,Rural,8.0,0.0,40.894968,"MULTIPOLYGON (((-50.20295 -23.24986, -50.20228..."
3,4.100103e+14,4100103.0,Abatiá,None,NaN,4.100103e+10,None,410010305.0,Abatiá,NaN,...,Santo Antônio da Platina,4105.0,Londrina,4.0,Sul,Rural,8.0,0.0,38.693760,"MULTIPOLYGON (((-50.26747 -23.30944, -50.26878..."
4,4.100103e+14,4100103.0,Abatiá,None,NaN,4.100103e+10,None,410010305.0,Abatiá,NaN,...,Santo Antônio da Platina,4105.0,Londrina,4.0,Sul,Rural,8.0,0.0,47.280182,"MULTIPOLYGON (((-50.34601 -23.29985, -50.34605..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23772,4.128807e+14,4128807.0,Xambrê,None,NaN,4.128807e+10,None,412880715.0,Eliza,NaN,...,Umuarama,4104.0,Maringá,4.0,Sul,Rural,8.0,0.0,3.388139,"MULTIPOLYGON (((-53.6102 -23.7295, -53.61562 -..."
23773,4.128807e+14,4128807.0,Xambrê,None,NaN,4.128807e+10,None,412880715.0,Eliza,NaN,...,Umuarama,4104.0,Maringá,4.0,Sul,Rural,8.0,0.0,35.975581,"MULTIPOLYGON (((-53.71643 -23.67371, -53.71724..."
23774,4.128807e+14,4128807.0,Xambrê,None,NaN,4.128807e+10,None,412880715.0,Eliza,NaN,...,Umuarama,4104.0,Maringá,4.0,Sul,Urbana,3.0,0.0,0.139743,"MULTIPOLYGON (((-53.71111 -23.71885, -53.71543..."
23775,4.128807e+14,4128807.0,Xambrê,None,NaN,4.128807e+10,None,412880715.0,Eliza,NaN,...,Umuarama,4104.0,Maringá,4.0,Sul,Rural,8.0,0.0,66.303877,"MULTIPOLYGON (((-53.56032 -23.77086, -53.57074..."
23776,4.128807e+14,4128807.0,Xambrê,None,NaN,4.128807e+10,None,412880715.0,Eliza,NaN,...,Umuarama,4104.0,Maringá,4.0,Sul,Rural,7.0,3.0,0.038548,"MULTIPOLYGON (((-53.59162 -23.79719, -53.59308..."

In [4]:
df.columns.tolist()

['code_tract',
 'code_muni',
 'name_muni',
 'name_neighborhood',
 'code_neighborhood',
 'code_subdistrict',
 'name_subdistrict',
 'code_district',
 'name_district',
 'code_urban_concentration',
 'name_urban_concentration',
 'code_state',
 'name_state',
 'code_immediate',
 'name_immediate',
 'code_intermediate',
 'name_intermediate',
 'code_region',
 'name_region',
 'situacao',
 'code_situacao',
 'code_type',
 'area_km2',
 'geometry']

In [5]:
df1 = gbr.read_statistical_grid(code_grid="PR", year=2010)

In [6]:
df1

,ID_UNICO,nome_1KM,nome_5KM,nome_10KM,nome_50KM,nome_100KM,nome_500KM,QUADRANTE,MASC,FEM,POP,DOM_OCU,geometry
0,200ME48190N88252,1KME4819N8825,5KME4815N8825,10KME4810N8820,50KME4800N8800,100KME4800N8750,500KME4800N8350,ID_24,0,0,0,0,"MULTIPOLYGON (((-55.75625 -22.50842, -55.75624..."
1,200ME48192N88252,1KME4819N8825,5KME4815N8825,10KME4810N8820,50KME4800N8800,100KME4800N8750,500KME4800N8350,ID_24,0,0,0,0,"MULTIPOLYGON (((-55.75431 -22.50843, -55.7543 ..."
2,200ME48194N88252,1KME4819N8825,5KME4815N8825,10KME4810N8820,50KME4800N8800,100KME4800N8750,500KME4800N8350,ID_24,0,0,0,0,"MULTIPOLYGON (((-55.75237 -22.50844, -55.75236..."
3,200ME48196N88252,1KME4819N8825,5KME4815N8825,10KME4810N8820,50KME4800N8800,100KME4800N8750,500KME4800N8350,ID_24,0,0,0,0,"MULTIPOLYGON (((-55.75043 -22.50846, -55.75042..."
4,200ME48198N88252,1KME4819N8825,5KME4815N8825,10KME4810N8820,50KME4800N8800,100KME4800N8750,500KME4800N8350,ID_24,0,0,0,0,"MULTIPOLYGON (((-55.74849 -22.50847, -55.74848..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220881,1KME5799N8845,1KME5799N8845,5KME5795N8845,10KME5790N8840,50KME5750N8800,100KME5700N8750,500KME5300N8350,ID_25,4,3,7,3,"MULTIPOLYGON (((-46.25452 -22.23272, -46.25478..."
1220882,1KME5799N8846,1KME5799N8846,5KME5795N8845,10KME5790N8840,50KME5750N8800,100KME5700N8750,500KME5300N8350,ID_25,4,3,7,2,"MULTIPOLYGON (((-46.25478 -22.22369, -46.25505..."
1220883,1KME5799N8847,1KME5799N8847,5KME5795N8845,10KME5790N8840,50KME5750N8800,100KME5700N8750,500KME5300N8350,ID_25,9,6,15,4,"MULTIPOLYGON (((-46.25505 -22.21465, -46.25532..."
1220884,1KME5799N8848,1KME5799N8848,5KME5795N8845,10KME5790N8840,50KME5750N8800,100KME5700N8750,500KME5300N8350,ID_25,0,0,0,0,"MULTIPOLYGON (((-46.25532 -22.20562, -46.25559..."
1220885,1KME5799N8849,1KME5799N8849,5KME5795N8845,10KME5790N8840,50KME5750N8800,100KME5700N8750,500KME5300N8350,ID_25,10,5,15,4,"MULTIPOLYGON (((-46.25559 -22.19659, -46.25586..."

In [1]:
import sidrapy

In [2]:
data = sidrapy.get_table(
                table_code="4709",
                territorial_level="6",
                ibge_territorial_code="all",
                variable="93"
            )

In [3]:
data

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N
0,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Variável (Código),Variável,Ano (Código),Ano
1,6,Município,45,Pessoas,21494,1100015,Alta Floresta D'Oeste - RO,93,População residente,2022,2022
2,6,Município,45,Pessoas,96833,1100023,Ariquemes - RO,93,População residente,2022,2022
3,6,Município,45,Pessoas,5351,1100031,Cabixi - RO,93,População residente,2022,2022
4,6,Município,45,Pessoas,86887,1100049,Cacoal - RO,93,População residente,2022,2022
...,...,...,...,...,...,...,...,...,...,...,...
5566,6,Município,45,Pessoas,14956,5222005,Vianópolis - GO,93,População residente,2022,2022
5567,6,Município,45,Pessoas,8768,5222054,Vicentinópolis - GO,93,População residente,2022,2022
5568,6,Município,45,Pessoas,4215,5222203,Vila Boa - GO,93,População residente,2022,2022
5569,6,Município,45,Pessoas,5815,5222302,Vila Propício - GO,93,População residente,2022,2022
5570,6,Município,45,Pessoas,2817381,5300108,Brasília - DF,93,População residente,2022,2022

In [6]:
df = data[1:].copy()

In [7]:
df

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N
1,6,Município,45,Pessoas,21494,1100015,Alta Floresta D'Oeste - RO,93,População residente,2022,2022
2,6,Município,45,Pessoas,96833,1100023,Ariquemes - RO,93,População residente,2022,2022
3,6,Município,45,Pessoas,5351,1100031,Cabixi - RO,93,População residente,2022,2022
4,6,Município,45,Pessoas,86887,1100049,Cacoal - RO,93,População residente,2022,2022
5,6,Município,45,Pessoas,15890,1100056,Cerejeiras - RO,93,População residente,2022,2022
...,...,...,...,...,...,...,...,...,...,...,...
5566,6,Município,45,Pessoas,14956,5222005,Vianópolis - GO,93,População residente,2022,2022
5567,6,Município,45,Pessoas,8768,5222054,Vicentinópolis - GO,93,População residente,2022,2022
5568,6,Município,45,Pessoas,4215,5222203,Vila Boa - GO,93,População residente,2022,2022
5569,6,Município,45,Pessoas,5815,5222302,Vila Propício - GO,93,População residente,2022,2022
5570,6,Município,45,Pessoas,2817381,5300108,Brasília - DF,93,População residente,2022,2022

In [8]:
df[["D1N", "UF"]] = df["D1N"].str.split(" - ", n=1, expand=True)

In [59]:
df

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,UF
1,6,Município,45,Pessoas,21494,1100015,Alta Floresta D'Oeste,93,População residente,2022,2022,RO
2,6,Município,45,Pessoas,96833,1100023,Ariquemes,93,População residente,2022,2022,RO
3,6,Município,45,Pessoas,5351,1100031,Cabixi,93,População residente,2022,2022,RO
4,6,Município,45,Pessoas,86887,1100049,Cacoal,93,População residente,2022,2022,RO
5,6,Município,45,Pessoas,15890,1100056,Cerejeiras,93,População residente,2022,2022,RO
...,...,...,...,...,...,...,...,...,...,...,...,...
5566,6,Município,45,Pessoas,14956,5222005,Vianópolis,93,População residente,2022,2022,GO
5567,6,Município,45,Pessoas,8768,5222054,Vicentinópolis,93,População residente,2022,2022,GO
5568,6,Município,45,Pessoas,4215,5222203,Vila Boa,93,População residente,2022,2022,GO
5569,6,Município,45,Pessoas,5815,5222302,Vila Propício,93,População residente,2022,2022,GO
5570,6,Município,45,Pessoas,2817381,5300108,Brasília,93,População residente,2022,2022,DF

In [37]:
df.loc[df["D1N"] == "Curitiba - PR"]

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,UF
4006,6,Município,45,Pessoas,1773718,4106902,Curitiba - PR,93,População residente,2022,2022,RO

In [60]:
dfpr = df.loc[df["UF"] == "PR"]

In [9]:
dfpr = df[df["UF"] == "PR"]

In [10]:
dfpr

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,UF
3913,6,Município,45,Pessoas,7241,4100103,Abatiá,93,População residente,2022,2022,PR
3914,6,Município,45,Pessoas,6256,4100202,Adrianópolis,93,População residente,2022,2022,PR
3915,6,Município,45,Pessoas,10233,4100301,Agudos do Sul,93,População residente,2022,2022,PR
3916,6,Município,45,Pessoas,119825,4100400,Almirante Tamandaré,93,População residente,2022,2022,PR
3917,6,Município,45,Pessoas,3590,4100459,Altamira do Paraná,93,População residente,2022,2022,PR
...,...,...,...,...,...,...,...,...,...,...,...,...
4307,6,Município,45,Pessoas,3055,4128625,Alto Paraíso,93,População residente,2022,2022,PR
4308,6,Município,45,Pessoas,5697,4128633,Doutor Ulysses,93,População residente,2022,2022,PR
4309,6,Município,45,Pessoas,3811,4128658,Virmond,93,População residente,2022,2022,PR
4310,6,Município,45,Pessoas,9706,4128708,Vitorino,93,População residente,2022,2022,PR
4311,6,Município,45,Pessoas,5798,4128807,Xambrê,93,População residente,2022,2022,PR

In [62]:
dfpr = dfpr.reset_index(drop=True)

In [63]:
dfpr

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,UF
0,6,Município,45,Pessoas,7241,4100103,Abatiá,93,População residente,2022,2022,PR
1,6,Município,45,Pessoas,6256,4100202,Adrianópolis,93,População residente,2022,2022,PR
2,6,Município,45,Pessoas,10233,4100301,Agudos do Sul,93,População residente,2022,2022,PR
3,6,Município,45,Pessoas,119825,4100400,Almirante Tamandaré,93,População residente,2022,2022,PR
4,6,Município,45,Pessoas,3590,4100459,Altamira do Paraná,93,População residente,2022,2022,PR
...,...,...,...,...,...,...,...,...,...,...,...,...
394,6,Município,45,Pessoas,3055,4128625,Alto Paraíso,93,População residente,2022,2022,PR
395,6,Município,45,Pessoas,5697,4128633,Doutor Ulysses,93,População residente,2022,2022,PR
396,6,Município,45,Pessoas,3811,4128658,Virmond,93,População residente,2022,2022,PR
397,6,Município,45,Pessoas,9706,4128708,Vitorino,93,População residente,2022,2022,PR
398,6,Município,45,Pessoas,5798,4128807,Xambrê,93,População residente,2022,2022,PR

In [11]:
dfpr[dfpr["D1N"] == "Foz do Iguaçu"]

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,UF
4031,6,Município,45,Pessoas,285415,4108304,Foz do Iguaçu,93,População residente,2022,2022,PR